linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/sirupsen/logrus
            desc: no logrus
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 120
    statements: 60
  interfacebloat:
    # The maximum number of methods allowed for an interface.
    # Default: 10
    max: 10
  godot:
    # Comments to be checked: `declarations`, `toplevel`, or `all`.
    # Default: declarations
    scope: declarations
    # List of regexps for excluding particular comment lines from check.
    # Default: []
    exclude:
      # Exclude to-do and fix-me comments.
      - "^fixme:"
      - "^todo:"
      - "nolint:"
    # Check that each sentence ends with a period.
    # Default: true
    period: false
    # Check that each sentence starts with a capital letter.
    # Default: false
    capital: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - typeDefFirst
      - paramTypeCombine
    settings:
      captLocal: # must be valid enabled check name
        # whether to restrict checker to params only (default true)
        paramsOnly: true
      elseif:
        # whether to skip balanced if-else pairs (default true)
        skipBalanced: true
      hugeParam:
        # size in bytes that makes the warning trigger (default 80)
        sizeThreshold: 80
      nestingReduce:
        # min number of statements inside a branch to trigger a warning (default 5)
        bodyWidth: 5
      rangeExprCopy:
        # size in bytes that makes the warning trigger (default 512)
        sizeThreshold: 512
        # whether to check test functions (default true)
        skipTestFuncs: true
      rangeValCopy:
        # size in bytes that makes the warning trigger (default 128)
        sizeThreshold: 128
        # whether to check test functions (default true)
        skipTestFuncs: true
      truncateCmp:
        # whether to skip int/uint/uintptr types (default true)
        skipArchDependent: true
      underef:
        # whether to skip (*x).method() calls where x is a pointer receiver (default true)
        skipRecvDeref: true
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
      - operation
      - assign
    ignored-numbers:
      - '2'
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  gomodguard:
    blocked:
      modules:
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
            reason: "see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules"
        - github.com/pkg/errors:
            recommendations:
              - errors
              - fmt
            reason: "Should be replaced by standard lib errors package"
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: true
    require-explanation: false
    require-specific: false
  dupl:
    threshold: 150
  goconst:
    min-len: 2
    min-occurrences: 2
  gocognit:
    min-complexity: 20
  gofmt:
    simplify: false
  varnamelen:
    max-distance: 20
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    check-receiver: true
    check-return: true
    check-type-param: true
    ignore-decls:
      - t testing.T
      - e error
      - i int
      - w http.ResponseWriter
      - r http.Request
  revive:
    ignore-generated-header: true
    severity: warning
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: argument-limit
        arguments: [9]
      - name: banned-characters
        disabled: true
      - name: confusing-naming
        disabled: true
      - name: comment-spacings
        disabled: true
      - name: cyclomatic
        arguments: [15]
      - name: file-header
        disabled: true
      - name: max-public-structs
        arguments: [10]
      - name: modifies-parameter
        disabled: true
      - name: function-length
        arguments: [50, 100]
      - name: function-result-limit
        arguments: [4]
      - name: line-length-limit
        arguments: [140]
      - name: cognitive-complexity
        arguments: [20]
      - name: defer
        arguments: [["loop", "call-chain", "recover", "return", "method-call"]]
linters:
  disable-all: true
  enable:
    - depguard
    - dupl
    - errorlint
    - funlen
    - goconst
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - prealloc
    - predeclared
    - dogsled
    - goprintffuncname
    - forbidigo
    - nolintlint
    - rowserrcheck
    - whitespace
    - asciicheck
    - sqlclosecheck
    - exhaustive
    - exportloopref
    - noctx
    - err113
    - mnd
    - gocyclo
    - nlreturn
    - wsl
    - gocognit
    - godot
    - gomodguard
    - godox
    - gochecknoglobals
    - gochecknoinits
    - durationcheck
    - nilerr
    - wastedassign
    - importas
    - promlinter
    - errname
    - gomoddirectives
    - gocritic
    - forcetypeassert
    - makezero
    - thelper
    - tparallel
    - bidichk
    - contextcheck
    - tenv
    - nilnil
    - grouper
    - decorder
    - nosprintfhostport
    - usestdlibvars
    - asasalint
    - reassign
    - containedctx
    - perfsprint
    - protogetter
    - spancheck
    - mirror
    - gocheckcompilerdirectives
    - errcheck
    - fatcontext
run:
  tests: false
issues:
  exclude-dirs-use-default: true
  exclude-files:
    - .*\.pb\.go$
    - .\_*easyjson\.go$
  exclude-dirs:
    - pkg
    - e2e
    - migrations
    - cmd/migrator